### ISSUE TITLE
Thin bottom line of menu-bar does not  apply new theme (non-client-area ?)

### ISSUE THREAD

**Issue by RaiKoHoff** [adzm/win32-custom-menubar-aero-theme#1]
Hello @adzm,
thank you very much for your solution.
It work fine for us (https://github.com/rizonesoft/Notepad3).
While most parts of the menu-bar now are rendered very well for dark-mode,
a thin line at the bottom of the menu-bar is not painted in defined colors:

![image](https://user-images.githubusercontent.com/8806350/134806200-0701a17c-21ab-4f43-94ae-f24838ea7388.png)

This line belongs to the menu-bar, cause it disappears on hiding the menu-bar:

![image](https://user-images.githubusercontent.com/8806350/134806257-6005ad0a-a3b7-4de5-8e11-02f79f2bf98e.png)

Maybe, it belongs to the "non client area" of the menu-bar ?
I found this:
https://stackoverflow.com/questions/57177310/how-to-paint-over-white-line-between-menu-bar-and-client-area-of-window

But I am not sure how to intercept the WM_NCPAINT message for the menu-bar (`WM_UAHNCPAINTMENUPOPUP` seems not to be called from the window proc 🤔).

Maybe, you have another solution for us?

**Comment by adzm** [comment]
Hello! Yes if you look at notepad plus plus we have a solution there that
simply overwrites the line.

**Comment by adzm** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9985 this is
how we implemented overwriting the white line in npp which should work fine
for you too!

Very happy to see this little thing I figured out getting used for dark
mode in apps!

**Comment by RaiKoHoff** [comment]
@adzm : Thank you very much for your hint - this works like charm.

**Comment by adzm** [comment]
Committed the solution to this repo as well
